### ISSUE TITLE
Implementar IPCA-15

### ISSUE THREAD

**Issue by cuducos** [cuducos/calculadora-do-cidadao#14]
Implementar adaptador para o [IPCA-15](https://www.ibge.gov.br/estatisticas/economicas/precos-e-custos/9256-indice-nacional-de-precos-ao-consumidor-amplo.html?=&t=downloads).

**Comment by rodolfo-viana** [comment]
Feito: #26

**Comment by cuducos** [comment]
Fechado no PR #29
