### ISSUE TITLE
Implementar cache

### ISSUE THREAD

**Issue by cuducos** [cuducos/calculadora-do-cidadao#16]
Definir um local padrão (pasta do usuário? raíz de execução do script?) e salvar um _pickle_ dos `Adapter.data`s para evitar fazer download a cada vez que for usar o projeto.

**Comment by cuducos** [comment]
Talvez [`appsdir`](https://pypi.org/project/appdirs/) possa ser uma solução, usando `user_cache_dir` – mas parece que a última versão tem alguns anos, então tem que testar a compatibilidade com as versões mais recentes do Python e dos sistemas operacionais.

**Comment by rodolfo-viana** [comment]
[`appsdir`](https://github.com/ActiveState/appdirs) teve atualização de `setup.py` há apenas 3 meses, para implementar Python 3.8 nos testes. Deve estar funcionando...

**Comment by cuducos** [comment]
Creio que a [função de importar/exportar](https://calculadora-do-cidadao.readthedocs.io/pt_BR/latest/usage.html#exportando-os-dados) supre a necessidade de cache (ao menos por enquanto).
