### ISSUE TITLE
Adicionar docstring

### ISSUE THREAD

**Issue by rodolfo-viana** [cuducos/calculadora-do-cidadao#20]
Antes de me dedicar aos outros índices vou atualizar o código inserindo `docstrings` para ficar no padrão da [PEP 257](https://www.python.org/dev/peps/pep-0257/). Tudo bem?

**Comment by cuducos** [comment]
Claro! Pode ir jogando aqui as dúvidas (tem coisa que deve estar só na minha cabeça ainda). E acho que podemos evitar falar de tipos nas _docstrings_ já que usei anotação de tipos em (quase?) todas as entradas e saídas. Adicionar essa redundância acho que só vai deixar mais complexa a manutenção (aumentar a chance de _docstring_ ficar desalinhada com assinatura da função).

**Comment by rodolfo-viana** [comment]
> E acho que podemos evitar falar de tipos nas docstrings já que usei anotação de tipos em (quase?) todas as entradas e saídas.

Sim, tem razão. Imagino evitar falar de tipos, mas sim de "o que aquilo faz no contexto geral", apenas para caso, no futuro, alguém queira mexer. :)
