### ISSUE TITLE
Raspador do SELIC tem que ser compatível com nova versão da Rows

### ISSUE THREAD

**Issue by cuducos** [cuducos/calculadora-do-cidadao#35]
O @turicas deu o toque:

> coluna `mesano` vai virar `mes_ano` com uma correção que fiz na rows (que tá no `develop`)

Precisamos de alguma alternativa para deixar esse trecho mais flexível (de repente ter um _fallback_ ou algo assim: 

https://github.com/cuducos/calculadora-do-cidadao/blob/c377a4eec2d7d69a96d17810e4b89bb07aa6b208/calculadora_do_cidadao/adapters/selic.py#L29-L30

**Comment by diraol** [comment]
Para ser bem sincero, eu não faria um fallback.

Podemos fixar a versão da rows que estamos usando por agora e quando a versão nova for lançada, quebrando a API da rows, indicamos a nova versão da rows como "mínima" e fazemos a alteração nos trechos de código correspondentes.

Acho mais razoável trabalhar com a dependência em termos de versão do que fallback entre versões.

Faz sentido?

**Comment by cuducos** [comment]
Total : )

**Comment by diraol** [comment]
Agora, para ser bem sincero, eu não achei referência em lugar nenhum a `mesano` ou `mes_ano` na `rows`...

**Comment by cuducos** [comment]
Não, o que muda lá é a forma que ela lê e transforma os cabeçalhos das colunas em nomes compatíveis com o namespace do Python ; )

**Comment by cuducos** [comment]
O adaptador da Selic mudou completamente devido a #53.
