### ISSUE TITLE
AttributeError: 'PosixPath' object has no attribute 'read_text'

### ISSUE THREAD

**Issue by cnd07** [cuducos/calculadora-do-cidadao#37]
Olá!
Tenho aqui instaladas as versões python 2.7 e 3.7, em Linux Mint Debian Edition 4.
Na instalação está dando erro:

jhh@jhhc:~$ sudo pip install calculadora-do-cidadao
[sudo] password for jhh:         
Collecting calculadora-do-cidadao
  Downloading https://files.pythonhosted.org/packages/0c/71/f57cff817008a0e8f7eadbbf654874de6804c256771933258eaff27ebe8f/calculadora-do-cidadao-0.4.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-9DyaE5/calculadora-do-cidadao/setup.py", line 20, in <module>
        long_description=Path("README.md").read_text(encoding="utf-8"),
    AttributeError: 'PosixPath' object has no attribute 'read_text'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-9DyaE5/calculadora-do-cidadao/

Parabenizo aos desenvolvedores pelo excelente trabalho e agradeço antecipadamente pela atenção.

**Comment by cuducos** [comment]
O [`PosixPath.read_text`](https://docs.python.org/3.8/library/pathlib.html#pathlib.PosixPath) existe desse de o Python 3.5. Então esse erro me leva a crer que o `pip` que você está usando é do Python 2.7, não do Python 3.7.

Já tentou `pip3`? Não sei muito como gerenciar versões do Python sem ser com o `pyenv`, mas algumas distribuições Linux tem `pip` e `pip3`…

**Comment by cnd07** [comment]
> O [`PosixPath.read_text`](https://docs.python.org/3.8/library/pathlib.html#pathlib.PosixPath) existe desse de o Python 3.5. Então esse erro me leva a crer que o `pip` que você está usando é do Python 2.7, não do Python 3.7.
> 
> Já tentou `pip3`? Não sei muito como gerenciar versões do Python sem ser com o `pyenv`, mas algumas distribuições Linux tem `pip` e `pip3`…

Era esse mesmo o problema - estava usando o pip do 2.7.
Instalado e utilizado o pip3, a instalação do calculadora-do-cidadao se deu sem problemas.
Grato pela pronta e efetiva resposta!
