### ISSUE TITLE
Arrumar os testes na CI

### ISSUE THREAD

**Issue by cuducos** [cuducos/calculadora-do-cidadao#43]
Rodando os testes locais, tudo passa, mas na CI tem algumas falhas de asserção ~~estranhas que dizem que `datetime.date(2018, 7, 6)` não é igual a `date(2018, 7, 6)` —~~ precisamos entender o porquê disso para tirar esse vermelhinho do _pipeline_ : )

```
>       assert DateField.deserialize(value) == date(2018, 7, 6)
E       AssertionError: assert datetime.date(2018, 7, 7) == datetime.date(2018, 7, 6)
E        +  where datetime.date(2018, 7, 7) = <bound method DateField.deserialize of <class 'calculadora_do_cidadao.fields.DateField'>>(1530925200)
E        +    where <bound method DateField.deserialize of <class 'calculadora_do_cidadao.fields.DateField'>> = DateField.deserialize
E        +  and   datetime.date(2018, 7, 6) = date(2018, 7, 6)
```

**Comment by diraol** [comment]
? Mas as datas ali são efetivamente diferentes....
uma é `2018-7-7` e a outra é `2018-7-6`, efetivamente um dia antes.

**Comment by cuducos** [comment]
Hum… verdade! Li tudo errado a saída do erro.
Talvez seja zica com fuso horário. Será?

**Comment by diraol** [comment]
Isso **sempre** é possível! hehehe

(Vou bater o olho lá no teste, ainda não fui ver)
