### ISSUE TITLE
Dependência da Rows

### ISSUE THREAD

**Issue by cuducos** [cuducos/calculadora-do-cidadao#51]
**Contexto**

A fantástica [Rows](https://github.com/turicas/rows) está [sem novas versões desde fevereiro de 2019](https://github.com/turicas/rows/releases/tag/v0.4.1). Um [_commit_ de lá, de abril de 2019](https://github.com/turicas/rows/commit/fcf226fdc779687df81ee586a31a8acf3f38f715), resolve um [problema de incompatibilidade com os Pythons mais novos](https://github.com/cuducos/calculadora-do-cidadao/runs/3702318596):

```
 tests/test_main.py:6: in <module>
    from calculadora_do_cidadao import (
calculadora_do_cidadao/__init__.py:1: in <module>
    from calculadora_do_cidadao.adapters.cpi import AllUrbanCityAverage  # noqa
calculadora_do_cidadao/adapters/__init__.py:8: in <module>
    from rows import export_to_csv, import_from_csv, import_from_dicts, import_from_html
../../../.cache/pypoetry/virtualenvs/calculadora-do-cidadao-WBmB8XYj-py3.9/lib/python3.9/site-packages/rows/__init__.py:22: in <module>
    import rows.plugins as plugins
../../../.cache/pypoetry/virtualenvs/calculadora-do-cidadao-WBmB8XYj-py3.9/lib/python3.9/site-packages/rows/plugins/__init__.py:24: in <module>
    from . import plugin_html as html
../../../.cache/pypoetry/virtualenvs/calculadora-do-cidadao-WBmB8XYj-py3.9/lib/python3.9/site-packages/rows/plugins/plugin_html.py:43: in <module>
    unescape = HTMLParser().unescape
E   AttributeError: 'HTMLParser' object has no attribute 'unescape'
```
**Problema**

Como o _commit_ é posterior ao último _release_, não temos uma versão publicada com esse ajuste para usar nas dependências da _Calculadora do Cidadão_. Tentar publicar um pacote que tem uma dependência que não tem uma versão, mas é instalada de um repositório Git com uma _branch_ ou _commit_ dá erro:

```
Publishing calculadora-do-cidadao (0.5.3) to PyPI
 - Uploading calculadora-do-cidadao-0.5.3.tar.gz 100%

  UploadError

  HTTP Error 400: Invalid value for requires_dist. Error: Can't have direct dependency: 'rows[csv,xls,html] @ git+https://github.com/turicas/rows.git@3a67d9dd65751e89281b28e3f1c30c4d6dc78e11'
 ```
 **Questões**

Vejo alguns caminhos, mas não considero nenhum uma solução ainda — então boto para debate e para colher ideais:
 
 * Criar um _fork_ da Rows para fazer releases mais constantes (não me agrada, muito trabalho, muita coisa para manter e rastro digital desnecessário)
 * Remover a dependência da Rows e utilizar outra solução para fazer a leitura dos HTMLs e XLS (caso fosse essa a solução, não gostaria que fosse o Pandas — muuuuuuita bazuca para essa questão, muita dependência viria junto; mas, fazer do zero é um reinventar a roda gigante) — talvez o [`frictionless`](https://pypi.org/project/frictionless/)
 * A Rows fazer um novo _release_ (só que isso não depende de mim… alô @turicas 💜)
 
 
O que acham?

**Comment by turicas** [comment]
Preciso de uma ajuda pra fazer uma nova release. Se puder parear por alguns minutos, fazemos juntos. :)

**Comment by cuducos** [comment]
Opa… _minutos_ mesmo? Se for, então vamos lá 💜 

Se quiser adiantar o que falta, aí me preparo e a gente faz isso!… Eu olhei no repo para tentar entender a situação, mas não consegui encontrar nada (vi os roadmaps para 0.5 e 0.6, procurei issues etc.).
