### ISSUE TITLE
Requerimentos

### ISSUE THREAD

**Issue by all0cer** [cuducos/calculadora-do-cidadao#52]
é sempre bom colocar um arquivo "requirements.txt" com as bibliotecas que precisam baixar ou mostrar as que importou e/ou versão das mesmas

**Comment by diraol** [comment]
Oi @all0cer, como definido na [documentação de contribuição do projeto](https://github.com/cuducos/calculadora-do-cidadao/blob/main/CONTRIBUTING.md), o projeto usa o padrão `pyproject.toml` e o [Poetry](https://python-poetry.org/) para gestão de dependências.

Então basta olhar no `pyproject.toml` na raiz do projeto.

**Comment by cuducos** [comment]
Exato, @all0cer — é o que o @diraol falou mesmo!

O `requirements.txt` tem alguns problemas, e optei por algo mais moderno, que é padrão na comunidade também: foi debatido na [PEP 621](https://peps.python.org/pep-0621/) e hoje faz parte da [documentação oficial](https://packaging.python.org/en/latest/specifications/declaring-project-metadata/#declaring-project-metadata) de _empacotamento_ de  bibliotecas.

Se tiver curiosidade sobre o assunto, essa _live_ do @dunossauro explica muito bem essa parte: [Ambientes virtuais e instalação de bibliotecas](https://youtu.be/naGF7EIUFp0)
