### ISSUE TITLE
Simplificar código que garante mês com dois dígitos

### ISSUE THREAD

**Issue by cuducos** [cuducos/calculadora-do-cidadao#6]
Seguindo [o exemplo do](https://gist.github.com/cuducos/1ab59c9080f93f9aa30ec38b732cd3c0#gistcomment-3123740) @diraol, não precisa, como está agora, explicitamente converter para `str` e, depois, usar `zfill` -- podemos usar f-strings com `:0>2d`.

**Comment by diraol** [comment]
Cara, nome de variável com acentuação. Vou dizer que foi ousado! :)

**Comment by cuducos** [comment]
Esse trecho:

https://github.com/cuducos/calculadora-do-cidadao/blob/b824b5b89e57c150f89be14cb824c7c3d193ed54/calculadora_do_cidadao.py#L39-L40

Pode ser simplesmente:

```python
        return f"{data.month:0>2d}/{data.year}" 
```

**Comment by cuducos** [comment]
> Cara, nome de variável com acentuação. Vou dizer que foi ousado! :)

Python 3, unicode por padrão. Só amor : )

Mas confesso que essa eu _roubei_ do @ramalho hehehe

**Comment by diraol** [comment]
Para quem trabalhou muito com Python2 vou te dizer que isso é mais que colírio para os olhos, é uma boa taça de vinho e uma bandeja cheia de queijos para acompanhar!

**Comment by diraol** [comment]
> > Cara, nome de variável com acentuação. Vou dizer que foi ousado! :)
> 
> Python 3, unicode por padrão. Só amor : )
> 
> Mas confesso que essa eu _roubei_ do @ramalho hehehe

Para quem trabalhou muito com Python2 vou te dizer que isso é mais que colírio para os olhos, é uma boa taça de vinho e uma bandeja cheia de queijos para acompanhar!
